name: DJ Yung Vamp
image: https://lucidmonday.files.wordpress.com/2020/12/dj-yung-vamp.jpg
urls:
  - https://djyungvamp.bandcamp.com/
  - https://soundcloud.com/djyungvampire13
  - https://open.spotify.com/artist/69eIrU4oA3mEHensYx0PWL
country: FR
