name: Rinse Cycle
image: https://i1.sndcdn.com/avatars-JdbJYmLaxzEg05pR-Vzcnhw-t500x500.jpg
urls:
  - https://soundcloud.com/rinse-cycle
  - https://open.spotify.com/artist/7LdE7z3rYGOa0R4u6Ev7aG
country: US
