name: iNFMS
image: https://i1.sndcdn.com/avatars-MydngkVW5K0r2Rh0-fpjQQg-t500x500.jpg
urls:
    - https://infms495.bandcamp.com
    - https://soundcloud.com/iaminfms
description: Donny Silverhand. lord infamous. The Don. the meanest, the prettiest, the badest mofo low down around this town.
country: US
