name: Necroez
image: https://i1.sndcdn.com/avatars-wXqN8r7cXzOmmzcl-VcqVFQ-t500x500.jpg
urls:
  - https://necroez.bandcamp.com/
  - https://soundcloud.com/necroez
  - https://open.spotify.com/artist/6mfg3kWylXNvu6hwrPEcTZ
country: BR
