name: Von Storm
image: https://i1.sndcdn.com/avatars-Oh6N5lA7md9LZKrt-yivKWg-t500x500.jpg
urls:
  - https://vonstorm.bandcamp.com/
  - https://soundcloud.com/vonstorm
  - https://open.spotify.com/artist/5acEBp4nbqoEjROkF8nLj4
country: US
