name: Syredu
image: https://i1.sndcdn.com/avatars-E96mq5xuXJEkJaUU-ht3eiw-t500x500.jpg
urls:
    - https://syredu.bandcamp.com
    - https://soundcloud.com/syredu
    - https://open.spotify.com/artist/6oVqN9kXX7pC7plIMZ4mKK
country: BR
