name: Puar
image: https://i1.sndcdn.com/avatars-FzaERErlhl7USLNb-ym65gQ-t500x500.jpg
urls:
  - https://puarbeats.bandcamp.com/
  - https://soundcloud.com/puarbeats
  - https://open.spotify.com/artist/2yvxxt7s9QjwEOZtLQ2yfT
  - https://www.youtube.com/channel/UCkmW4JJ3liVLrXC-S6KR1mQ
country: CA
