name: DJ Smokey
image: https://dailychiefers.com/wp-content/media/2017/08/Screen-Shot-2017-08-31-at-4.34.59-PM.png
country: CA
urls:
    - https://djsmokey.bandcamp.com
    - https://soundcloud.com/smoke-gang-beatz
    - https://open.spotify.com/artist/6o5wSBDuLpn2vRpPvGuGBy
