name: Sappy
image: https://i1.sndcdn.com/avatars-000208234185-6s81si-t500x500.jpg
urls:
    - https://sappy94.bandcamp.com/
    - https://soundcloud.com/sappy94
    - https://open.spotify.com/artist/0YZ7sZXDlZ8nDjhcrFhUBG
