name: Existanze
image: https://i1.sndcdn.com/avatars-oyPmOMAOMOzSWBvZ-cQxcFw-t500x500.jpg
urls:
  - https://existanze.bandcamp.com/
  - https://soundcloud.com/existanze
  - https://open.spotify.com/artist/1FnM99NJwEfH34iJDxSeAk
