name: Giovane Six
image: https://f4.bcbits.com/img/0021601242_10.jpg
urls:
    - https://giovane666.bandcamp.com/music
    - https://soundcloud.com/giovane666
    - https://open.spotify.com/artist/6Jn7nJG3L4wKq1Ar58UUrd
    - https://music.apple.com/us/artist/giovane-six/1473603551
country: IT
