name: NDKS
image: https://i1.sndcdn.com/avatars-000753181021-8bduw3-t500x500.jpg
urls:
    - https://ndks.bandcamp.com
    - https://soundcloud.com/indeksjunts
    - https://open.spotify.com/artist/7954b5FunWdQcWIP1z5m4J
