name: Redhands
image: https://i1.sndcdn.com/avatars-000621574563-d6mr76-t500x500.jpg
urls:
    - https://itsreallyredhands.bandcamp.com/
    - https://soundcloud.com/itsreallyredhands
    - https://open.spotify.com/artist/6eu9b9mi9h4yN5VVdEgtUa
country: CA
