name: Backwhen
image: https://i1.sndcdn.com/avatars-khzIf9MQptFKNezj-0YOynA-t500x500.jpg
urls:
    - https://bamdcamp.bandcamp.com/
    - https://soundcloud.com/backwhen808
    - https://open.spotify.com/artist/47T694aNABbLrqSh4Di7Xj
country: US
