name: Holy Mob
image: https://f4.bcbits.com/img/0012176292_10.jpg
urls:
    - https://holymob.bandcamp.com/
    - https://soundcloud.com/holymob
    - https://open.spotify.com/artist/2Ar5DBAoGWXQU38kyXA0ad
description: Underground producer collective.
collective_members:
    - name: caspian-rose
    - name: gali
    - name: inteus
    - name: lvks
    - name: necroez
    - name: ponsuda
    - name: redhands
    - name: sheltr
    - name: vedebe
    - name: von-storm
