name: Soudire
image: https://i.discogs.com/BIOLEUbP6iNoo2met_JiwA5K_AfmJ1x-O48oJbr0J1w/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTU3OTgz/NzYtMTU3MTkzMzU5/OS03NzE1LmpwZWc.jpeg
urls:
  - https://soudiere.bandcamp.com/
  - https://soundcloud.com/youngpirelli
  - https://open.spotify.com/artist/01oeaKF2UI2pmIHljhewRN
  - https://music.apple.com/us/artist/soudiere/1178719512
  - https://www.youtube.com/channel/UCidBqEPSPtIF2mwgw58PALQ
country: FR
