name: Everyst
image: https://i1.sndcdn.com/avatars-NkqBuWR5ci1RMGNN-HpU2Bg-t500x500.jpg
urls:
    - https://everyst.bandcamp.com
    - https://open.spotify.com/artist/1QgQF1oyo7at7bSwEeO7YX
    - https://music.apple.com/us/artist/everyst/1529042501
country: US
state: GA
city: Atlanta
