name: 1ony
image: https://f4.bcbits.com/img/0013727905_10.jpg
urls:
  - https://1ony.bandcamp.com/
  - https://soundcloud.com/1ony
  - https://open.spotify.com/artist/7hwhgBwy9Qi98HD1HzAOrt
  - https://music.apple.com/us/artist/1ony/1414106754
country: KZ
