name: ZappBeats
image: https://i1.sndcdn.com/avatars-wPsbJJZMHacsmzrh-ZwQzGA-t500x500.jpg
urls:
  - https://zappbeats.bandcamp.com/
  - https://soundcloud.com/zappbeats
  - https://open.spotify.com/artist/2Bkja0HKcOvssKxruT3c7Y
country: CA
