name: RVFVEL
image: https://i.scdn.co/image/ab6761610000e5eb9fbb137f2f67145ad14bc7db
urls:
  - https://soundcloud.com/rvfvelbeats
  - https://open.spotify.com/artist/0wwqAXGpSicBgsdrkRQKpg
country: FI
