name: Sheltr.
image: https://f4.bcbits.com/img/0010130147_10.jpg
urls:
  - https://sheltr666.bandcamp.com/
  - https://soundcloud.com/sheltr666
  - https://open.spotify.com/artist/2cOl755F5lE2SDD0YTIIa1
country: US
