name: Local Stranger
image: https://i1.sndcdn.com/avatars-Ud2FjnjByqKD1RsU-yTi61w-t500x500.jpg
country: US
state: IL
urls:
    - https://lxcalstranger.bandcamp.com/
    - https://soundcloud.com/lxcalstranger
    - https://open.spotify.com/artist/6P9GghZhEj3Ckb8XLafWyR
