name: Seithèn
image: https://pbs.twimg.com/profile_images/1595621376630702081/dpgKf03R_400x400.jpg
urls:
  - https://soundcloud.com/holyseithen
  - https://open.spotify.com/artist/3isqSPbzQrea0MG4D8IUyK
