name: Re_V
image: https://f4.bcbits.com/img/0029585959_10.jpg
urls:
    - https://revbeatz.bandcamp.com
    - https://soundcloud.com/revbeatz
    - https://open.spotify.com/artist/5Oe7vzlYBvzQOkxu6aIoP4
