name: OGee-T
image: https://f4.bcbits.com/img/0018839591_10.jpg
urls:
  - https://ogee-t.bandcamp.com/
  - https://soundcloud.com/ogee-t
  - https://open.spotify.com/artist/1SRRBqqhQfgeQTze2FRsNX
  - https://www.youtube.com/channel/UCuHU2v7XVe6nkVZwNJNCL5Q
country: FA
