name: skeler.
image: https://lastfm.freetls.fastly.net/i/u/ar0/fbe3b4a91348de58e8b6014ed025be34.jpg
urls:
    - https://skelermusic.bandcamp.com
    - https://soundcloud.com/skelermusic
    - https://open.spotify.com/artist/7ks4LdnBvp6HUsmVJiKgsB
country: AU
