name: Purple Posse
image: https://f4.bcbits.com/img/0006986466_10.jpg
logo: https://imgur.com/upWFLf7.png
urls:
    - https://purpleposse.bandcamp.com/
    - https://soundcloud.com/purpleposse
    - https://open.spotify.com/artist/4bCHCFBbYL3TL6YjOen6UU
collective_members:
    - name: soudiere
    - name: "666"
    - name: aseri
    - name: gravy
    - name: backwhen
    - name: dj-vung-vamp
      joined: 2018
    - name: caspian-rose
      joined: 2017
    - name: shaq-france
    - name: backwood-boy
    - name: 1ony
      joined: 2018
    - name: seithen
    - name: jak3
      left: 2017
