name: Motat
image: https://i1.sndcdn.com/avatars-B7HE7OKTW37ruG5E-6hboaQ-t500x500.jpg
urls:
  - https://motat.bandcamp.com
  - https://soundcloud.com/motatnz
  - https://open.spotify.com/artist/55IdwQj2L2u1dIkMTOZmvn
country: NZ
city: Auckland
