name: Backwood Boy
image: https://i1.sndcdn.com/avatars-slKR2m4yBKedLbnS-MC9aaA-t500x500.jpg
urls:
  - https://backwoodboy.bandcamp.com/
  - https://soundcloud.com/backwoodboi
  - https://open.spotify.com/artist/1HTit70rVYspYlcG78l9kD
  - https://music.apple.com/au/artist/backwood-boy/1299171618
country: UA
