name: Squid
image: https://i1.sndcdn.com/avatars-Kry9wD2vdccPvJYM-C3qjZA-t500x500.jpg
urls:
    - https://squidiotic.bandcamp.com
    - https://soundcloud.com/squidiotic
    - https://music.apple.com/us/artist/squid/1555419087
    - https://open.spotify.com/artist/4CvBT9f8gpCwz1WpFJmYlS
country: CA
