name: Caspian Rose
image: https://scontent-lga3-1.cdninstagram.com/v/t51.2885-19/258606815_251235403735618_7953869193630879378_n.jpg?stp=dst-jpg_s320x320&_nc_ht=scontent-lga3-1.cdninstagram.com&_nc_cat=110&_nc_ohc=DQTvhNqsnboAX9EdaAj&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AfACbudzXdeVcNgl0AU7RQxmXiPukSKc0flPBiNZqd9Omg&oe=63B04359&_nc_sid=8fd12b
urls:
  - https://soundcloud.com/caspianrose
