name: Inteus
image: https://i1.sndcdn.com/avatars-jSZjgzrnH3LRsZcl-3pcdVg-t500x500.jpg
urls:
    - https://inteus-holymob.bandcamp.com
    - https://soundcloud.com/inteus666
    - https://open.spotify.com/artist/19NNBW45HcAOPkYzJMeMNN
country: US
