name: OPEN
image: https://f4.bcbits.com/img/0022175504_10.jpg
urls:
    - https://prodopen.bandcamp.com
    - https://soundcloud.com/prodopen
    - https://open.spotify.com/artist/45J3RsBe0vydwBadMB7vFA
country: BR
