name: Vedebe
image: https://i1.sndcdn.com/avatars-gpbGbDzzQBYB3Egb-43tQFA-t500x500.jpg
urls:
  - https://vedebe.bandcamp.com/
  - https://soundcloud.com/vedebe98
  - https://open.spotify.com/artist/50bIkZeTvW3iPm8VAVlILS
country: DE
