name: Wobase
image: https://i1.sndcdn.com/avatars-67pU4z1EFa2nTmyS-AvROFQ-t500x500.jpg
urls:
    - https://wobase.bandcamp.com
    - https://soundcloud.com/wobase
    - https://open.spotify.com/artist/15fc1w1SMWHBUo1mEZ8A8q
country: FI
