name: lu9ius
image: https://i1.sndcdn.com/avatars-O6kfKbkaHblFTnEg-88spXw-t500x500.jpg
urls:
  - https://soundcloud.com/lu9ius
  - https://open.spotify.com/artist/3hEfPS3Xn3PsQa23RUXvR9
  - https://music.apple.com/us/artist/lu9ius/1533976721
  - https://www.youtube.com/channel/UCPwvIZ0tEPvNirNaY18e71w
country: FR
