name: Kvnvshimi
image: https://f4.bcbits.com/img/0027676070_10.jpg
urls:
  - https://soundcloud.com/kanashimilol
  - https://kvnvshimi.bandcamp.com
  - https://open.spotify.com/artist/0Zxy1GwwJq1KaRoyhoogir
country: PL
city: Wrocław
