name: Menthalo
image: https://i1.sndcdn.com/avatars-OfyUxtWwhXSgzmC4-Q8LZRg-t500x500.jpg
urls:
    - https://menthalo.bandcamp.com
    - https://soundcloud.com/menthalo666
    - https://open.spotify.com/artist/59LVnvRGRKhr9AFD3KP6u4
country: FR
