name: l v k s
image: https://i1.sndcdn.com/avatars-0Ozze7pQXmKXJnUd-UJOgzg-t500x500.jpg
urls:
  - https://soundcloud.com/lvksound
  - https://open.spotify.com/artist/2jBeI2BKUvT4JDOhPb3TXt
country: BR
