name: Crimson Crew
image: https://i.imgur.com/7P3Nkwm.png
logo: https://i.imgur.com/7P3Nkwm.png
urls:
    - https://soundcloud.com/crimsoncrew666
    - https://crimsoncrew.bandcamp.com/
description: Crimson Crew is a collective with some phonk/trap producers and rappers.
collective_members:
    - name: re_v
    - name: zappbeats
    - name: sxlvr
    - name: scales
    - name: infms
    - name: petsmpi
    - name: destro
    - name: prodichigo
    - name: erickd
    - name: feals
    - name: dr-f
    - name: winter
    - name: dopxset
    - name: sternn
    - name: raccoo
    - name: freddy-konfeddy
